# Generated by Django 6.0.5 on 2026-06-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_analysisevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugreport',
            name='report_type',
            field=models.CharField(choices=[('bug', 'Bug'), ('suggestion', 'Verbesserung')], default='bug', max_length=20),
        ),
    ]
