# Generated by Django 6.0.5 on 2026-07-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_bugreport_report_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='consent_training',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='files_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
