# Generated by Django 6.0.5 on 2026-07-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_project_consent_training_project_files_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugreport',
            name='client_info',
            field=models.TextField(blank=True),
        ),
    ]
