# Generated by Django 6.0.5 on 2026-07-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_bugreport_client_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugreport',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
