# Generated by Django 6.0.5 on 2026-07-24 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_feedbackresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackresponse',
            name='role',
            field=models.CharField(blank=True, choices=[('energieberater', 'Energieberater'), ('architekt', 'Architekt'), ('bauleiter', 'Bauleiter'), ('handwerker', 'Handwerker'), ('sonstiges', 'Sonstiges')], max_length=32, verbose_name='Rolle'),
        ),
        migrations.AlterField(
            model_name='feedbackresponse',
            name='improve',
            field=models.TextField(verbose_name='Wo gab es Probleme/Unklarheiten?'),
        ),
        migrations.AlterField(
            model_name='feedbackresponse',
            name='missing',
            field=models.TextField(verbose_name='Welche Funktion fehlt?'),
        ),
        migrations.AlterField(
            model_name='feedbackresponse',
            name='positive',
            field=models.TextField(verbose_name='Was gefällt am besten?'),
        ),
    ]
