# Generated by Django 6.0.5 on 2026-07-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_feedbackresponse_role_alter_feedbackresponse_improve_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackresponse',
            name='role_other',
            field=models.CharField(blank=True, max_length=120, verbose_name='Rolle (Sonstiges)'),
        ),
    ]
