# Generated by Django 6.0.5 on 2026-07-27 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_feedbackresponse_role_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackresponse',
            name='role',
            field=models.CharField(blank=True, choices=[('energieberater', 'Energieberatung'), ('architekt', 'Architektur'), ('bauleiter', 'Bauleitung'), ('handwerker', 'Handwerk'), ('sonstiges', 'Sonstiges')], max_length=32, verbose_name='Rolle'),
        ),
    ]
