# Generated by Django 6.0.5 on 2026-07-11 16:00

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='max_projects',
            field=models.PositiveIntegerField(default=accounts.models.default_max_projects, help_text='Max. Anzahl online gespeicherter Projekte für diesen User.'),
        ),
    ]
