# Generated by Django 6.0.5 on 2026-07-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_subscription_max_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
