# Generated by Django 6.0.5 on 2026-08-14 07:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_subscription_email_verified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='discount_percent',
            field=models.PositiveSmallIntegerField(default=0, help_text='0 = kein Rabatt.', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Rabatt (%)'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='discount_reason',
            field=models.CharField(blank=True, help_text='Interne Notiz, z.B. "Beta-Tester" oder "Mengenrabatt 8 Lizenzen".', max_length=100, verbose_name='Rabatt-Grund'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='discount_scope',
            field=models.CharField(choices=[('once', 'Einmalig (nur die nächste Jahreslizenz)'), ('lifetime', 'Dauerhaft (jede Verlängerung)')], default='once', max_length=10, verbose_name='Rabatt-Laufzeit'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='discount_used_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Rabatt eingelöst am'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='list_price_chf',
            field=models.PositiveIntegerField(blank=True, help_text='Leer = aktueller Listenpreis (LICENSE_PRICE_CHF).', null=True, verbose_name='Basispreis (CHF/Jahr)'),
        ),
    ]
