# Generated by Django 6.0.5 on 2026-08-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_subscription_discount_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='list_price_chf',
            field=models.PositiveIntegerField(blank=True, help_text='Leer = aktueller Listenpreis (LICENSE_PRICE_CHF). Wird bei der ersten Verlängerung automatisch festgeschrieben; leeren, um das Konto auf den heutigen Listenpreis zu heben.', null=True, verbose_name='Basispreis (CHF/Jahr)'),
        ),
    ]
