# Generated by Django 6.0.5 on 2026-08-14 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_subscription_list_price_chf'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='billing_city',
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AddField(
            model_name='subscription',
            name='billing_company',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='subscription',
            name='billing_country',
            field=models.CharField(default='CH', max_length=2),
        ),
        migrations.AddField(
            model_name='subscription',
            name='billing_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='subscription',
            name='billing_street',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='subscription',
            name='billing_zip',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='Rechnungsnummer')),
                ('status', models.CharField(choices=[('open', 'Offen'), ('paid', 'Bezahlt'), ('cancelled', 'Storniert')], default='open', max_length=10)),
                ('issued_on', models.DateField(verbose_name='Rechnungsdatum')),
                ('due_on', models.DateField(verbose_name='Zahlbar bis')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Bezahlt am')),
                ('net_chf', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Netto')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='MWST-Satz (%)')),
                ('vat_chf', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='MWST')),
                ('total_chf', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Total')),
                ('period_start', models.DateField(verbose_name='Lizenz von')),
                ('period_end', models.DateField(verbose_name='Lizenz bis')),
                ('list_price_chf', models.PositiveIntegerField(verbose_name='Basispreis')),
                ('discount_percent', models.PositiveSmallIntegerField(default=0)),
                ('discount_note', models.CharField(blank=True, max_length=200)),
                ('billing_company', models.CharField(blank=True, max_length=100)),
                ('billing_name', models.CharField(max_length=100)),
                ('billing_street', models.CharField(max_length=70)),
                ('billing_zip', models.CharField(max_length=16)),
                ('billing_city', models.CharField(max_length=35)),
                ('billing_country', models.CharField(default='CH', max_length=2)),
                ('billing_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_on', '-number'],
            },
        ),
    ]
