# Generated by Django 6.0.5 on 2026-08-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_subscription_billing_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='creditor',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='invoice',
            name='creditor_iban',
            field=models.CharField(blank=True, default='', max_length=34),
        ),
        migrations.AddField(
            model_name='invoice',
            name='creditor_vat_uid',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
