# Generated by Django 6.0.5 on 2026-08-20 19:03

from django.db import migrations, models


def backfill_previous_paid_until(apps, schema_editor):
    """Altrechnungen mit der früheren Storno-Heuristik befüllen.

    Bis jetzt riet `cancel_invoices` den Vorzustand aus `period_start`: liegt
    er nach dem Rechnungsdatum, schloss die Rechnung an eine laufende Lizenz
    an, sonst gab es vorher keine. Genau das wird hier eingefroren — für alte
    Rechnungen ist es die beste verfügbare Information, und danach steht auf
    jeder Zeile ein Wert, sodass NULL eindeutig "vorher keine Lizenz" heisst.
    """
    Invoice = apps.get_model('accounts', 'Invoice')
    for invoice in Invoice.objects.all():
        if invoice.period_start > invoice.issued_on:
            invoice.previous_paid_until = invoice.period_start
            invoice.save(update_fields=['previous_paid_until'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_invoice_creditor_invoice_creditor_iban_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='previous_paid_until',
            field=models.DateField(blank=True, null=True, verbose_name='Lizenz vor dieser Rechnung'),
        ),
        migrations.RunPython(backfill_previous_paid_until,
                             migrations.RunPython.noop),
    ]
